<?php
// Curated wordlist for system-generated recovery phrases (Diceware-style).
// Simple, memorable, lowercase words. The phrase is RANDOMLY generated by the
// server (not chosen by the user) so it carries real entropy.
return [
    // animals
    'ant', 'bat', 'bear', 'bee', 'bird', 'bison', 'boar', 'bull', 'camel', 'cat',
    'cheetah', 'chicken', 'cobra', 'cow', 'crab', 'crane', 'crow', 'deer', 'dog', 'dolphin',
    'donkey', 'dove', 'duck', 'eagle', 'eel', 'elk', 'falcon', 'ferret', 'finch', 'fish',
    'flamingo', 'fox', 'frog', 'gecko', 'goat', 'goose', 'gorilla', 'hamster', 'hare', 'hawk',
    'hedgehog', 'heron', 'horse', 'hyena', 'ibis', 'iguana', 'jaguar', 'jay', 'koala', 'lamb',
    'lark', 'lemur', 'leopard', 'lion', 'lizard', 'llama', 'lynx', 'magpie', 'mole', 'monkey',
    'moose', 'moth', 'mouse', 'mule', 'newt', 'otter', 'owl', 'panda', 'panther', 'parrot',
    'peacock', 'pelican', 'penguin', 'pig', 'pigeon', 'pony', 'puffin', 'puma', 'quail', 'rabbit',
    'raccoon', 'ram', 'rat', 'raven', 'robin', 'salmon', 'shark', 'sheep', 'shrew', 'skunk',
    'sloth', 'snail', 'snake', 'sparrow', 'spider', 'squid', 'stork', 'swan', 'tiger', 'toad',
    'trout', 'turkey', 'turtle', 'viper', 'vole', 'vulture', 'walrus', 'wasp', 'weasel', 'whale',
    'wolf', 'wombat', 'worm', 'wren', 'yak', 'zebra',
    // nature
    'acorn', 'amber', 'aurora', 'autumn', 'bay', 'beach', 'berry', 'birch', 'bloom', 'breeze',
    'brook', 'canyon', 'cave', 'cedar', 'cliff', 'cloud', 'clover', 'coast', 'comet', 'coral',
    'creek', 'dawn', 'delta', 'desert', 'dew', 'dune', 'dusk', 'earth', 'ember', 'fern',
    'fjord', 'flame', 'flower', 'fog', 'forest', 'frost', 'galaxy', 'garden', 'glacier', 'glade',
    'grove', 'hill', 'ice', 'island', 'ivy', 'jungle', 'lagoon', 'lake', 'leaf', 'lily',
    'lotus', 'marsh', 'meadow', 'mist', 'moon', 'moss', 'mountain', 'oak', 'ocean', 'palm',
    'peak', 'pebble', 'petal', 'pine', 'pond', 'prairie', 'rain', 'reef', 'ridge', 'river',
    'rock', 'root', 'rose', 'sand', 'sea', 'seed', 'shore', 'sky', 'snow', 'spring',
    'star', 'stone', 'storm', 'stream', 'summit', 'sun', 'swamp', 'thorn', 'thunder', 'tide',
    'tree', 'tundra', 'valley', 'vine', 'wave', 'willow', 'wind', 'wood',
    // objects
    'anchor', 'arrow', 'axe', 'badge', 'basket', 'bell', 'blade', 'boat', 'book', 'bottle',
    'bowl', 'bridge', 'brush', 'candle', 'cannon', 'cape', 'chain', 'chair', 'clock', 'coin',
    'compass', 'crown', 'cup', 'dagger', 'dial', 'drum', 'feather', 'flag', 'flask', 'flute',
    'gem', 'glass', 'glove', 'hammer', 'harp', 'helmet', 'jar', 'kettle', 'key', 'kite',
    'lamp', 'lantern', 'lens', 'lock', 'map', 'mask', 'mirror', 'needle', 'oar', 'pearl',
    'pen', 'pillar', 'plate', 'prism', 'quill', 'ring', 'rope', 'sail', 'scroll', 'shield',
    'ship', 'spoon', 'sword', 'table', 'torch', 'tower', 'trumpet', 'vase', 'wagon', 'wheel',
    'whistle',
];
